apiVersion: camel.apache.org/v1alpha1
kind: Kamelet
metadata:
  name: connector-kafka-source
  annotations:
    camel.apache.org/provider: "Red Hat"
    camel.apache.org/kamelet.version: "${connector.kamelets.version}"
  labels:
    camel.apache.org/kamelet.type: "source"
spec:
  definition:
    title: "Managed Kafka Source"
    description: |-
      Receive data from Managed Kafka topics.
    required:
      - topic
    type: object
    properties:
      topic:
        title: Topic Names
        description: A comma-separated list of Kafka topic names.
        type: string
  dependencies:
    - "camel:kafka"
    - "camel:kamelet"
  template:
    beans:
      - name: "kc"
        type: "#class:org.apache.camel.component.kafka.KafkaComponent"
        properties:
          createConsumerBackoffInterval: "3000"
          createConsumerBackoffMaxAttempts: "100"
          subscribeConsumerBackoffInterval: "3000"
          subscribeConsumerBackoffMaxAttempts: "100"
      - name: "kafka-client-factory"
        type: "#class:com.github.sco1237896.connector.kamelet.kafka.ClientFactory"
        properties:
          bootstrapUrl: "{{bootstrapServers}}"
          registryUrl: '{{registryUrl:}}'
          username: '{{user}}'
          password: '{{password}}'
    from:
      uri: "{{kc}}:{{topic}}"
      parameters:
        securityProtocol: "{{securityProtocol:SASL_SSL}}"
        saslMechanism: "{{saslMechanism:PLAIN}}"
        saslJaasConfig: "org.apache.kafka.common.security.plain.PlainLoginModule required username='{{user}}' password='{{password}}';"
        autoOffsetReset: "{{autoOffsetReset:latest}}"
        groupId: "{{?consumerGroup}}"
        keyDeserializer: "{{keyDeserializer:org.apache.kafka.common.serialization.ByteArrayDeserializer}}"
        valueDeserializer: "{{valueDeserializer:com.github.sco1237896.connector.kamelet.serdes.bytes.ByteArrayDeserializer}}"
        kafkaClientFactory: "#{{kafka-client-factory}}"
        headerDeserializer: "#class:com.github.sco1237896.connector.kamelet.kafka.ToStringHeaderDeserializer"
        pollOnError: "{{pollOnError:RECONNECT}}"
      steps:
      - removeHeader:
          name: "kafka.HEADERS"
      - to: "kamelet:sink"
